FROM eclipse-temurin:17-jre-jammy AS runner
EXPOSE 8090
RUN addgroup --system spring && adduser --system --ingroup spring spring

WORKDIR /app
COPY ./api-gateway/build/libs/api-gateway-*.jar /app/app.jar
COPY ./api-gateway/entrypoint.sh /app/entrypoint.sh
COPY ./wait-for-it.sh /app/wait-for-it.sh

# FORZAR PERMISOS
RUN chmod +x /app/entrypoint.sh /app/wait-for-it.sh && \
    chown spring:spring /app/app.jar /app/entrypoint.sh /app/wait-for-it.sh

USER spring:spring
ENTRYPOINT ["/app/entrypoint.sh"]