server:
  port: ${AUTH_PORT:8081}

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${AUTH_DB_HOST:db_auth}:5432/${AUTH_DB_NAME:auth}
    username: ${AUTH_DB_USERNAME:auth_user}
    password: ${AUTH_DB_PASSWORD:auth_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Observability
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_EUREKA:http://discovery-service:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

app:
  jwt:
    secret: ${JWT_SECRET:======================CelottsJWTSecretDefaultDevKey===========================}
    expirationMs: 86400000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://zipkin:9411/api/v2/spans}

logging:
  level:
    com.celotts: INFO
    org.springframework.web: INFO
