server:
  port: 9094

spring:
  application:
    name: purchase-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-purchase:5432/purchase}
    username: ${SPRING_DATASOURCE_USERNAME:purchase}
    password: ${SPRING_DATASOURCE_PASSWORD:purchase123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
