FROM eclipse-temurin:17-jre-jammy AS runner
EXPOSE 8086
RUN addgroup --system spring && adduser --system --ingroup spring spring

WORKDIR /app
COPY ./sales-service/build/libs/sales-service-*.jar /app/app.jar
COPY ./sales-service/entrypoint.sh /app/entrypoint.sh
COPY ./wait-for-it.sh /app/wait-for-it.sh

# FORZAR PERMISOS (Soluciona OCI permission denied)
RUN chmod +x /app/entrypoint.sh /app/wait-for-it.sh && \
    chown spring:spring /app/app.jar /app/entrypoint.sh /app/wait-for-it.sh

USER spring:spring
ENTRYPOINT ["/app/entrypoint.sh"]