

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    networks:
      - inventory-network

  discovery-service:
    image: inventory/discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    networks:
      - inventory-network

  config-service:
    image: inventory/config-service
    ports:
      - "7777:7777"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DISCOVERY_SERVICE_HEALTH_URL=http://discovery-service:8761/actuator/health
    depends_on:
      - discovery-service
    networks:
      - inventory-network

  product-db:
    image: postgres:16
    environment:
      - POSTGRES_DB=product
      - POSTGRES_USER=product
      - POSTGRES_PASSWORD=product123
    ports:
      - "5432:5432"
    volumes:
      - product-data:/var/lib/postgresql/data
    networks:
      - inventory-network

  product-service:
    image: inventory/product-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/product
      - SPRING_DATASOURCE_USERNAME=product
      - SPRING_DATASOURCE_PASSWORD=product123
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:7777
      - JAVA_OPTS=-Xms128m -Xmx256m
    depends_on:
      - discovery-service
      - config-service
      - product-db
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge

volumes:
  product-data:
  portainer_data: