FROM eclipse-temurin:17-jre-jammy AS runner
EXPOSE 9090
RUN addgroup --system spring && adduser --system --ingroup spring spring
WORKDIR /app
COPY ./product-service/build/libs/product-service-*.jar /app/app.jar
COPY ./product-service/entrypoint.sh /app/entrypoint.sh
COPY ./wait-for-it.sh /app/wait-for-it.sh
RUN chmod +x /app/entrypoint.sh /app/wait-for-it.sh && chown spring:spring /app/entrypoint.sh /app/wait-for-it.sh
USER spring:spring
ENTRYPOINT ["/app/entrypoint.sh"]