server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # No se registra a sí mismo
    fetch-registry: false       # No busca otros registros
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0 # Arranca de inmediato
