server:
  port: ${PRODUCT_PORT:9090}

spring:
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET:======================CelottsJWTSecretDefaultDevKey===========================}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_EUREKA:http://discovery-service:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    com.celotts: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
