server:
  port: 8086

spring:
  application:
    name: sales-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-sales:5432/sales}
    username: ${SPRING_DATASOURCE_USERNAME:sales_user}
    password: ${SPRING_DATASOURCE_PASSWORD:sales_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
